### PR TITLE
Fix failing connections

### PR DESCRIPTION
**Pull request by luyikei**
The type of data.proxy is QPointer, which is different from FcitxQtInputContextProxy, therefore causing a compile error.

### CODE REVIEW

**Comment by wengxt** [comment]
I have no problem with that. What's the version of your qt and compiler?

**Comment by luyikei** [comment]
qmake --version
QMake version 3.0
Using Qt version 5.5.0 in /usr/local/lib

**Comment by luyikei** [comment]
make --version
GNU Make 3.81

**Comment by luyikei** [comment]
g++ --version
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.1) 4.8.4

**Pull request closed without merging**
